export interface InformationEntity {
  fatherName: string,
  fatherHeight: number,
  motherName: string,
  motherHeight: number,
  phoneNumber: string,
  fullName: string,
  currentHeight: number,
  currentWeight: number,
  gender?: string,
  date_of_birth: string,
  currentProduct: string,
  sport?: string,
  timeSleep?: string,
}